### ISSUE TITLE
Error to launch on MacOS10.13

### ISSUE THREAD

**Issue by ishandutta2007** [dmr99/electron-react-boilerplate#1]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

The app to lunch without any console errors

## Current Behavior

The app lunchs but with console errors and blank screen

The following error is seen in the devtools console

```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at Object.injectIntoGlobalHook (react-refresh-runtime.development.js:449:1)
    at ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js (ReactRefreshEntry.js:17:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:4:1
    at startup:10:1
    at webpackUniversalModuleDefinition (universalModuleDefinition:7:1)
    at universalModuleDefinition:10:2

```
## Steps to Reproduce

```
git clone --depth 1 --branch main https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name
cd your-project-name
npm install
npm start
```

## Context

I am just setting up on Macos10.13 . New user of this repo.

## Your Environment

- Node version : v16.20.2
- electron-react-boilerplate version or branch : latest main branch
- Operating System and version : MacOS10.13.6

**Comment by ishandutta2007** [comment]
addressed here https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3028
